// frontend-vue/src/views/auth/register.vue
<script setup>

//import reactive and ref from vue
import { reactive, ref } from 'vue'

//import useRouter from vue router
import { useRouter } from 'vue-router'

//inisialisasi vue router on Composition API
const router = useRouter()

//import services api
import api from '../../services/api'

//state user
const user = reactive({
    name: '',
    username: '',
    email: '',
    password: '',
    password_confirmation: ''
})

//state validation
const validation = ref([])

//method register
const register = async () => {

    //call api register
    await api.post('/api/register', {
        name: user.name,
        username: user.username,
        email: user.email,
        password: user.password,
    })
        .then(() => {
            //redirect ke halaman login
            router.push({
                name: 'login'
            })
        })
    .catch(error => {
        //assign validation value with error
        validation.value = error.response.data
    })

}

</script>

<template>
    <div class="container">
        <div class="py-5 text-center">
            <img class="d-block mx-auto mb-4" src="../../assets/vue.svg" alt="" width="72" height="57">
            <h2>Register form</h2>
            <p class="lead">Below is an example form built entirely with Bootstrap’s form controls. Each required form group has a validation state that can be triggered by attempting to submit the form without completing it.</p>
        </div>
        <div v-if="validation.errors" class="mt-2 alert alert-danger">
            <ul class="mt-0 mb-0">
                                <li v-for="(error, index) in validation.errors" :key="index">
                                    {{ `${error.path} : ${error.msg}` }}
                                </li>
                            </ul>
        </div>
        <div class="row g-5">
            <div class="col-md-12 col-lg-12">
                <form class="needs-validation" @submit.prevent="register">
                    <div class="row g-3">
                        <div class="col-12">
                            <label for="firstName" class="form-label">Full Name</label>
                            <input type="text" class="form-control" v-model="user.name" placeholder="" value="" required>
                            <div class="invalid-feedback">
                                Valid fullname is required.
                            </div>
                        </div>

                        <div class="col-12">
                        <label for="username" class="form-label">Username</label>
                            <div class="input-group has-validation">
                                <span class="input-group-text">@</span>
                                <input type="text" class="form-control" v-model="user.username" placeholder="Username" required>
                            <div class="invalid-feedback">
                                Your username is required.
                                </div>
                            </div>
                        </div>

                        <div class="col-12">
                            <label for="email" class="form-label">Email</label>
                            <input type="email" class="form-control" v-model="user.email" placeholder="you@example.com" required>
                            <div class="invalid-feedback">
                                Please enter a valid email address
                            </div>
                        </div>

                        <div class="col-12">
                            <label for="address" class="form-label">Password</label>
                            <input type="password" v-model="user.password" class="form-control" placeholder="Password" />
                        </div>

                        
                    </div>

                    <hr class="my-4">

                    <button class="w-100 btn btn-primary btn-lg" type="submit">Register</button>
                </form>
            </div>
        </div>
    </div>
</template>

// frontend-react/src/views/auth/register.jsx
//import hook react
import React, { useState } from "react";

//import hook useNavigate from react router dom
import { useNavigate } from "react-router-dom";

//import services api
import api from '../../services/api'

export default function Register() {

    //navigate
    const navigate = useNavigate();

    //define state
    const [name, setName] = useState("");
    const [username, setUsername] = useState("");
    const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");

    //define state validation
    const [validation, setValidation] = useState([]);

    //function "register"
    const register = async (e) => {
        e.preventDefault();

        //call api register
        await api.post('/api/register', {
            name: name,
            username: username,
            email: email,
            password: password,
        })
            .then(() => {
                //redirect ke halaman login
                navigate("/login");
            })
        .catch(error => {
            //assign error to state "validation"
            setValidation(error.response.data);
        })
    };

    return (
        <div className="row justify-content-center">
            <div className="row justify-content-center">
                <div className="col-md-5">
                    <div className="card border-0 rounded shadow-sm">
                        <div className="card-body">
                            <h4>REGISTER</h4>
                            <hr />
                            {
                                validation.errors && (
                                    <div className="alert alert-danger mt-2 pb-0">
                                        {
                                            validation.errors.map((error, index) => (
                                                <p key={index}>{error.path} : {error.msg}</p>
                                            ))
                                        }
                                    </div>
                                )
                            }
                            <form onSubmit={register}>
                                <div className="row">
                                    <div className="col-md-12 mb-3">
                                        <div className="form-group">
                                            <label className="mb-1 fw-bold">Full Name</label>
                                            <input type="text" value={name} onChange={(e) => setName(e.target.value)} className="form-control"
                                                placeholder="Full Name" />
                                        </div>
                                    </div>
                                </div>
                                <div className="row">
                                    <div className="col-md-12 mb-3">
                                        <div className="form-group">
                                            <label className="mb-1 fw-bold">Email address</label>
                                            <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="form-control"
                                                placeholder="Email Address" />
                                        </div>
                                    </div>
                                </div>

                                <div className="row">
                                    <div className="col-md-6 mb-3">
                                        <div className="form-group">
                                            <label className="mb-1 fw-bold">Username</label>
                                            <input type="text" value={username} onChange={(e) => setUsername(e.target.value)} className="form-control"
                                                placeholder="Username" />
                                        </div>
                                    </div>
                                    <div className="col-md-6 mb-3">
                                        <div className="form-group">
                                            <label className="mb-1 fw-bold">Password</label>
                                            <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="form-control"
                                                placeholder="Password" />
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" className="btn btn-primary w-100">REGISTER</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}
